### ISSUE TITLE
Sandboxed File/Directory Path

### ISSUE THREAD

**Issue by feross** [WICG/native-file-system#10]
One thing that could improve this API is an option to use a sandbox filesystem, similar to what the deprecated FileSystem API used to do.

Maybe we can add a `{sandbox: true}` or `{temp: true}` option that would store the file to a browser sandbox location without prompting the user.

Basically, everything would be the same, except the browser would not prompt the user for a file/directory location. Instead, the browser would just immediately return a sandboxed file/directory location.

Just set one option, and the browser will pick a path for you.

**Comment by mkruisselbrink** [comment]
I do agree that this is something we might want to consider. It would essentially be something like the (chrome only) [`requestFileSystem`](https://www.w3.org/TR/2012/WD-file-system-api-20120417/#widl-LocalFileSystem-requestFileSystem-void-unsigned-short-type-unsigned-long-long-size-FileSystemCallback-successCallback-ErrorCallback-errorCallback) method, that returns a directory reference to a quota-managed and origin scoped sandboxed filesystem. Perhaps not in the initial version though, as it doesn't really help solve any new use cases. Although it might make testing easier (both for testing bits of this API as well as for people wanting to test code using these new writable file APIs).

**Comment by jimmywarting** [comment]
I like the idea of a sandboxed Directory
But i would also want to control wether or not it should be temporary or persistent also. so i think both could be used. `{sandbox: true, temp: true}` or `{sandbox: true, persistent: true}`

using `temp` instead of `sandbox` is just confusing and is not the right word.

**Comment by jespertheend** [comment]
The use case described here https://bugs.chromium.org/p/chromium/issues/detail?id=897313#c16 might require the use of a sandboxed file/direcotry.
I was wondering though, if we do end up adding some kind of way to open files with an external program from the browser, we might need to communicate to the user somehow that the opened file can still be accessed from the browser.

**Comment by mkruisselbrink** [comment]
Closing this, since we do have a sandboxed filesystem in the spec now.
