### ISSUE TITLE
FR: Provide append functionality

### ISSUE THREAD

**Issue by OldSparkyMI** [WICG/native-file-system#114]
The documentation of the native file system does not provide any write - append functionality, so e.g.: 
```
save(first, second, third) {
    ...
    writer.write(0, first);
    writer.write(first.length, second);
    writer.write(first.length + second.length, third);
```
is much harder to read or implement than:
```
save(first, second, third) {
  ...
  writer.write(0, first);
  writer.append(second);
  writer.append(third);
```
or
```
save(first, second, third) {
  ...
  writer.write(0, first);
  writer.write(-1, second);
  writer.write(-1, third);
```
Or do I miss something in the documentation?
See: https://wicg.github.io/native-file-system/#api-filesystemwriter-write

**Comment by foolip** [comment]
Funny, I just filed https://github.com/WICG/native-file-system/issues/124 and this code is an example of precisely the sort of code that wouldn't work as expected with some strings. But what I suggested there would still make it cumbersome, an implicit write position would solve this better.

**Comment by OldSparkyMI** [comment]
You are absolutely right. That is the reason why I used pseudo code.

But I still like an append function, because if you just wanna append content to a existing file, you have to get the file size from the File object, instead of just calling append.

**Comment by mkruisselbrink** [comment]
While appending to an existing file is still not very performant due to how we only support atomic writes, the awkward having to keep track of the current file size is no longer there with the new WritabelStream based writing API. Now by default writes are done at the end of the previous write operation.
