### ISSUE TITLE
Purpose of FileSystemHandle's isFile and isDirectory?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#116]
https://wicg.github.io/native-file-system/#api-filesystemhandle now looks like this:
```webidl
[Exposed=(Window,Worker), SecureContext, Serializable]
interface FileSystemHandle {
  readonly attribute boolean isFile;
  readonly attribute boolean isDirectory;
  readonly attribute USVString name;

  Promise<PermissionState> queryPermission(optional FileSystemHandlePermissionDescriptor descriptor = {});
  Promise<PermissionState> requestPermission(optional FileSystemHandlePermissionDescriptor descriptor = {});
};
```

`handle.isFile` is equivalent to `handle instanceof FileSystemFileHandle`, so is this just for convenience? If it is a mere convenience, I wonder if a `kind` enum would be an improvment, as it's possible to `switch` on its value?

Surprisingly I couldn't find this bikeshedded in any issue yet :)

**Comment by rektide** [comment]
I like how the current situation leaves the door open for people to create their own non-native files & directories. 

If I am a [cloud hosting provider](https://github.com/WICG/native-file-system/issues/123) trying to build a management interface, maybe I want to create a MyCloudFileSystemFileHandle. And maybe it's not easy to derive it from FileSystemFileHandle. `.isFile` remains a good way for me to indicate the file-ness of these handles.

**Comment by mkruisselbrink** [comment]
> `handle.isFile` is equivalent to `handle instanceof FileSystemFileHandle`

That is only true of `handle` and `FileSystemFileHandle` were created in the same realm. But having said that, I'm not tied to any particular shape of brand-checking API. But for FileSystemDirectoryHandle.getEntries() to be usable it does seem like we need some kind of brand-checking API.
