### ISSUE TITLE
Define FileSystemHandle serialization steps

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#117]
This issue is effectively to fix the TODOs in https://wicg.github.io/native-file-system/#api-filesystemhandle.

In doing so, https://wicg.github.io/native-file-system/#privacy-third-party should probably be updated and https://github.com/WICG/native-file-system/issues/92 closed.

**Comment by mkruisselbrink** [comment]
I think this was addressed. Although I'm not sure what you think needs to be updated in that privacy section?
