### ISSUE TITLE
Let write() resolve with the number of bytes written?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#124]
[`write()`](https://wicg.github.io/native-file-system/#dom-filesystemwriter-write) resolves with undefined, but in particular for USVString it's non-trivial to know how many bytes were written, and it would be tempting to assume `data.length` which would be correct for ASCII and perhaps accidentally correct in some cases involving surrogate pairs.

It should be easy to write a bunch of data and knowing how much was written:
```js
let position = 0;
for (const data of listOfThing) {
  const written = await writer.write(position, data);
  position += written;
}
await writer.close();
```

`position` is now hopefully the size of the file in bytes. But notice how tempting it is to use `data.length` to avoid the extra variable, which might be necessary in a more complicated case not using `await`...

**Comment by mkruisselbrink** [comment]
Not sure how feasible having a non-void return type would be now we're having a write API based on WritableStream... Hopefully no longer having to pass in an explicit position when calling write makes it less likely that people would make mistakes like this.
