### ISSUE TITLE
Is file/directory creation recursive like mkdir -p?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#126]
https://wicg.github.io/native-file-system/#api-filesystemdirectoryhandle-getfile has a TODO for the normative definition, and one question I'd like to see answered is whether only the leaf file/directory is created with `{ create: true }` or if all missing parent directories are also created? Or does it just not work to have slashes/backspaces in names?

**Comment by mkruisselbrink** [comment]
You can't have slashes in the name. But that reminds me, while #168 does try to normatively define these methods, it currently doesn't do any verification of passed in names being valid. I need to add that.
