### ISSUE TITLE
Guarantees when racing write/truncate/close?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#130]
This is like https://github.com/WICG/native-file-system/issues/128 but for the methods of [`FileSystemWriter`](https://wicg.github.io/native-file-system/#api-filesystemwriter).

A particularly interesting case here is whether it's OK to write or truncate to a bunch of positions at the same time where the "position is past the end of the file" condition might be triggered for one of the writes, but where serializing all the writes would not.

I believe the sensible behavior is to provide ordering guarantees, ensuring the outcome is the same as if the calls had been done in series.

**Comment by mkruisselbrink** [comment]
The new API and normative spec based on writable streams uses their internal queueing, which I believe should address what happens here.
