### ISSUE TITLE
In close(), what counts as "file on disk changed"?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#131]
[`close()`](https://wicg.github.io/native-file-system/#api-filesystemwriter-close) is a TODO for normative text, and one thing I'd expect to need quite a lot of detail is what counts as "file on disk changed". It could be one of:
- file name or content is currently not what it was when it was opened
- file name or content was different some time between now and when it was opened
- file modification time is not the same as when it was opened, although file contents might be the same

**Comment by mkruisselbrink** [comment]
Close does have normative text now (threaded through writable streams), and we actually didn't implemented (nor specified) the described behavior. Not sure if we should bring something like this back though. It does seem like a potentially nice backstop against data loss, but it might also result in unexpected (and hard to debug) errors for developers...
