### ISSUE TITLE
What does "contents will be cleared" mean?

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#132]
For [`chooseFileSystemEntries()`](https://wicg.github.io/native-file-system/#dom-window-choosefilesystementries) there's non-normative text that says:
> When set to "save-file" the dialog will additionally let the user select files that don’t yet exist, and if the user selects a file that does exist already, its contents will be cleared before the handle is returned to the website.

What does clearing entail? Will the file be of length zero even if the site then doesn't write anything to it? That seems problematic, resulting in data loss if the site fails to reach the `close()` call.

This seems to me like a case for [write-only handles](https://github.com/WICG/native-file-system/issues/119), in which case the content wouldn't need to be cleared.

**Comment by mkruisselbrink** [comment]
I'm not sure why that is problematic? Yes, if you have buggy websites you might have data-loss, but that wouldn't be that much different if we didn't clear the file until the websites tells us to. I.e. a website that reaches close() to soon would cause the same data loss in either case... Both cases the user asked a website to nuke a file and replace it with whatever data the website wants to replace it with, so from the users point of view this doesn't seem to make any difference?
