### ISSUE TITLE
Odd mention of IndexedDB

### ISSUE THREAD

**Issue by foolip** [WICG/native-file-system#135]
https://wicg.github.io/native-file-system/#privacy-tracking says:
> This risk is somewhat mitigated by the fact that clearing browsing data will also clear IndexedDB

This seems odd, is there a special connection to IndexedDB, or should this refer to clearing any site data/storage?

**Comment by mkruisselbrink** [comment]
The special connection is that IndexedDB is the only storage in which you can currently store these handles. But I agree that that sentence could use some rephrasing/clearing up.
