### ISSUE TITLE
Native FileSystem Api InvalidStateError on File Modification via "directory"

### ISSUE THREAD

**Issue by kishok** [WICG/native-file-system#140]
the native file system API throws the following error when my disk space is around 16% left. But it was working earlier when I had little extra space, but not sure on threshold of failure. Below is the error i had

> An operation that depends on state cached in an interface object was made but the state had changed since it was read from disk.

 **Please note that this issue affects only folder access and not file access**. I tired the same with my C drive which 25.8% space, it worked. Not sure, if it matters but the size of the folder that we are loading is 6.76 GB but we are only reading the specific files(count:3) from it. 

**Steps To Reproduce:**
After folder access, we are try to change and save some files in the file system...
BTW - the bug is on Windows 
Chrome version: 78
OS Version: Windows 10

What might cause this?

Is there any quota limit to use this API?

**Comment by oyiptong** [comment]
Hi @kishok,

The Native File System API would only affect quota limits if the Sandboxed Filesystem is used when writing to disk.

Could the file have changed while the file was being read?

Also, can you please post a code snippet and reproduction steps @ https://crbug.com/

We’ll be glad to look into the issue.

**Comment by kishok** [comment]
i have raised issue in chromium bug tracker. Please check below link for issue details with code snippet and reproduction steps
https://bugs.chromium.org/p/chromium/issues/detail?id=1036822

Please let us know if you require any additional information/queries.

**Comment by mkruisselbrink** [comment]
Closing this in favor of the chromium bug.
