### ISSUE TITLE
Error "The User aborted the request"

### ISSUE THREAD

**Issue by LucaJunge** [WICG/native-file-system#143]
When I try to choose a directory with my smartphone to display the filenames, I get the above error.
The Native File System is enabled in my chrome Browser (v79) and my Domain has an origin trial enabled.

I noticed that Chrome Canary removed the mention of "Android" in the Native File System API Description in chrome://flags. Is it no longer supported on Android devices? Because it works on my desktop pc. I was unable to find any information on this topic.

**Comment by inexorabletash** [comment]
The Chrome origin trial does not include Android support. This is called out in the "Intent to Experiment" thread.
