### ISSUE TITLE
The API should allow working with absolute paths

### ISSUE THREAD

**Issue by destan** [WICG/native-file-system#145]
I think there should be a way to get absolute paths of files and directories. Maybe a new method on `FileSystemFileHandle` and `FileSystemDirectoryHandle`.
Also, `chooseFileSystemEntries` would be better if it accepts an absolute path (of a file or directory) so the file picker would open the file or directory pre-selected.

Consider [Text editor](https://googlechromelabs.github.io/text-editor/) example. If you were to implement a _multiple project_ feature where the editor remembers the folders of different projects and opens the last used project. Very much like modern IDEs. So how would you do it? Every time you  would need to ask user for the project folder. However, if we could know and keep the absolute path of the project folder we can open the file picker with the project folder pre-selected and all the user has to do is to accept it.

Being able to know absolute paths would allow us in PWAs to backup/sync users' folder, project etc. preferences.

**Comment by Eloque** [comment]
In favor of this. In my use case, I am monitoring one folder and based on some logic, will move some files to another folder. 

Currently, this works fine, but I have no way to store the source and target folders. Having to re-ask permissions after a reload is fine, but asking the user to re-input the locations every time the app is used, is bothersome.

**Comment by fernap3** [comment]
Seems to me like the use cases mentioned are valid, but I feel that access to absolute paths without the user's consent may be a security concern.

**Comment by destan** [comment]
> Seems to me like the use cases mentioned are valid, but I feel that access to absolute paths without the user's consent may be a security concern.

I wouldn't have any problem with an API that requires user consent like location does.

**Comment by mkruisselbrink** [comment]
The way the spec attempts to support the mentioned use cases is by allowing you to store handles in IndexedDB. That way you don't need access to absolute paths, and we don't need to provide a way to give access to an absolute path, but instead you can store the handle itself. This is currently mostly implemented behind a flag in chrome, and will involve re-asking for permissions as mentioned. There won't be any need to re-input locations though.

Is there any use case I'm missing that isn't addressed by this?

**Comment by mh-cbon** [comment]
I need that feature too, absolute file path.

I am having an app in secure context, the user has to choose a folder, its absolute path is then forwarded to the backend for "the business". The backend does not care of a file handle.

I was thrilled to replace my odious textarea to input the directory path with that new API : / I am less thrilled to re invent the wheel = ) Hope you can figure out a way to make it really cool.

As a site note, i am really not interested in running electron.... Also <input id="myFile" type="file" webkitdirectory /> does not seem to be a good solution, when i select a directory it seems to import the whole tree within the browser.

**Comment by jespertheend** [comment]
@mkruisselbrink I think the situation described in the OP is a good use case. VSCode would also benefit from this, its electron version has an option to right click files and select ‘copy path’ from the context menu. Would be nice to have this available on its web version as well.
