### ISSUE TITLE
 ChooseFileSystemEntriesType types are implemented as camelCase, but spec'ed as hyphen-separated

### ISSUE THREAD

**Issue by tomayac** [WICG/native-file-system#147]
`ChooseFileSystemEntriesType` is spec'ed as hyphen-separated (e.g., `"open-file"`), but implemented as camelCased (e.g., `"openFile"`). Choose one.

**Comment by mkruisselbrink** [comment]
We didn't want to break backwards compatibility during the origin trial, so while M78/79/80 only support camelCased, M81 will support both and from M82 onward (when we're hoping to roll out a new origin trial) only hyphen-separated will be supported.
