### ISSUE TITLE
A `File` needs a pointer back to its `FileSystemHandle`

### ISSUE THREAD

**Issue by tomayac** [WICG/native-file-system#148]
For the `File` resulting from a call to `await fileHandle.getFile()`, there's no way back to the ` FileSystemHandle`, forcing library authors to [store the handle somewhere](https://github.com/tomayac/browser-nativefs/blob/c1058a5873c8068842537f7acbf717e0d9d97f07/src/file-open-nativefs.mjs#L44). It would be nice if `File` had a readonly `handle` [attribute](https://w3c.github.io/FileAPI/#attributes-blob) that would allow for [intuitive open-edit-save flows](https://github.com/excalidraw/excalidraw/blob/5bd1c8b3cd29a9a08be78fb3de32bcc86553cb6f/src/scene/data.ts#L53-L60). I realize this is more of a [File API](https://w3c.github.io/FileAPI/) issue, but since `FileSystemHandle` is spec'ed here, I start the discussion here.

**Comment by mkruisselbrink** [comment]
I'm curious to understand more of what you're trying to do here. In general I wouldn't expect anybody to ever hold on to the `File` object long-term (or call `getFile()` pre-emptively). `File` objects are conceptually snapshots, every time you save to the file (or otherwise modify the file on disk) you'll have to call `getFile()` again to get a new valid `File` object.

**Comment by tomayac** [comment]
Note that this is not about holding on to the `File` object itself, but indeed to store a reference to a `File`'s `FileSystemHandle` so that eventually one can write back to it. Here's a [deep link](https://github.com/excalidraw/excalidraw/blob/5bd1c8b3cd29a9a08be78fb3de32bcc86553cb6f/src/scene/data.ts#L83-L84). The idea is to have the file opening code (with a fallback to `<input type="file">`) in one module, and as a common denominator return `File`s objects.

**Comment by jimmywarting** [comment]
Not sure this is necessary or not.
I don't think the intent is to save the File somewhere but instead save the FileSytemFileHandle

FileSytemFileHandle should keep track of the File not the other way around...?

But to tackle your senario I would maybe have used WeakMap to do what you need to do
```js
const wm = new WeakMap()
const fileHandle = await chooseFileSystemEntries({ type:'openFile' })
const file = await fileHandle.getfile()
wm.set(file, fileHandle)

// later
fileHandle = wm.get(file)

// or simply just have an object: 
{ fileHandle, file }
```

(haven't played around looked much with native fs)

**Comment by tomayac** [comment]
Thanks for the feedback. The situation will also improve once `FileSystemHandle `s can be stored.

**Comment by mkruisselbrink** [comment]
Closing this issue. Nothing stops you from storing a FileSystemHandle on the File object yourself, so it doesn't seem like there would be much benefit in providing that automatically.
