### ISSUE TITLE
chooseFileSystemEntries should be allowed to give a name hint

### ISSUE THREAD

**Issue by tomayac** [WICG/native-file-system#149]
By specifying a value for the [`download` attribute of an anchor](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-download) (example: `<a download="foo.txt">`), one can suggest a file name for the to-be-downloaded file.

It would be useful if a similar option was available for saving files via `chooseFileSystemEntries`, possible as a new field `fileName` in `ChooseFileSystemEntriesOptions`.

**Comment by secumundo** [comment]
I agree. I was a little surprised that his is currently not possible. Further experimenting with the API on hold :(

**Comment by jimmywarting** [comment]
dupe: #80?

**Comment by tomayac** [comment]
> dupe: #80?

Dupe indeed (sorry for not searching diligently enough before opening a new issue). Closing mine in favor of #80.
