### ISSUE TITLE
Ability to open files into web apps from desktop side as well 

### ISSUE THREAD

**Issue by brettz9** [WICG/native-file-system#15]
Not sure whether you'd want to include it within this proposal, but it may be of interest to at least make mention of supporting the opening of desktop files (from the desktop side) into web apps.

A while back, I implemented this (at the time, for Windows) as a Firefox SDK add-on, WebAppFind for which I had a bunch of demos working for viewing and editing binary as well as text files.

(The permission to edit was established for that browser session only (similar to how desktop applications normally do not continue to act on a given file once the file is closed), but I'd like to allow an option for remembering such permissions, so the web app could track/list files opened previously in this manner.)

However, with breaking API changes by Firefox, I have been doing some work on a [re-implementation](https://github.com/brettz9/webappfind/tree/v3.0.0-webext) (currently, it is minimally functional, though this time, focusing on the Mac, given my change in dev environment).

Some health issues slow my progress considerably, but I'd love to share/discuss the approach if it is interesting, whether in relation to your project or in general.

Best wishes,
Brett

**Comment by mgiuca** [comment]
@ewilligers FYI

**Comment by mkruisselbrink** [comment]
This is addressed in https://github.com/WICG/file-handling/blob/master/explainer.md, so closing this issue.
