### ISSUE TITLE
TypeScript types

### ISSUE THREAD

**Issue by jakearchibald** [WICG/native-file-system#151]
Here are TypeScript types for the current spec (aside from the system directory stuff). Feel free to close if this isn't useful, but it might save someone else time if they're looking for it.

```ts
type ChooseFileSystemEntriesType = 'open-file' | 'save-file' | 'open-directory';

interface ChooseFileSystemEntriesOptionsAccepts {
  description?: string;
  mimeTypes?: string[];
  extensions?: string[];
}

interface ChooseFileSystemEntriesOptions {
  type?: ChooseFileSystemEntriesType;
  multiple?: boolean;
  accepts?: ChooseFileSystemEntriesOptionsAccepts[];
  excludeAcceptAllOption?: boolean;
}

interface ChooseFileSystemEntriesOptionsMultiple
  extends ChooseFileSystemEntriesOptions {
  multiple: true;
}

interface ChooseFileSystemEntriesOptionsDirectory
  extends ChooseFileSystemEntriesOptions {
  type: 'open-directory';
  multiple?: false;
}

interface ChooseFileSystemEntriesOptionsDirectoryMultiple
  extends ChooseFileSystemEntriesOptions {
  type: 'open-directory';
  multiple: true;
}

interface ChooseFileSystemEntriesOptionsFile
  extends ChooseFileSystemEntriesOptions {
  type?: 'open-file' | 'save-file';
  multiple?: false;
}

interface ChooseFileSystemEntriesOptionsFileMultiple
  extends ChooseFileSystemEntriesOptions {
  type?: 'open-file' | 'save-file';
  multiple: true;
}

interface FileSystemHandlePermissionDescriptor {
  writable?: boolean;
}

interface FileSystemHandle {
  readonly isFile: boolean;
  readonly isDirectory: boolean;
  readonly name: string;

  queryPermission(
    descriptor?: FileSystemHandlePermissionDescriptor,
  ): Promise<PermissionState>;
  requestPermission(
    descriptor?: FileSystemHandlePermissionDescriptor,
  ): Promise<PermissionState>;
}

interface FileSystemCreateWriterOptions {
  keepExistingData?: boolean;
}

interface FileSystemFileHandle extends FileSystemHandle {
  readonly isFile: true;
  readonly isDirectory: false;

  getFile(): File;
  createWriter(
    options?: FileSystemCreateWriterOptions,
  ): Promise<FileSystemWriter>;
}

interface FileSystemGetFileOptions {
  create?: boolean;
}

interface FileSystemGetDirectoryOptions {
  create?: boolean;
}

interface FileSystemRemoveOptions {
  recursive?: boolean;
}

interface FileSystemDirectoryHandle extends FileSystemHandle {
  readonly isFile: false;
  readonly isDirectory: true;

  getFile(
    name: string,
    options?: FileSystemGetFileOptions,
  ): Promise<FileSystemFileHandle>;
  getDirectory(
    name: string,
    options?: FileSystemGetDirectoryOptions,
  ): Promise<FileSystemDirectoryHandle>;
  getEntries(): AsyncIterable<FileSystemDirectoryHandle | FileSystemFileHandle>;
  removeEntry(name: string, options?: FileSystemRemoveOptions): Promise<void>;
}

interface FileSystemWriter {
  write(position: number, data: BufferSource | Blob | string): Promise<void>;
  truncate(size: number): Promise<void>;
  close(): Promise<void>;
}

declare function chooseFileSystemEntries(
  options?: ChooseFileSystemEntriesOptionsFile,
): Promise<FileSystemFileHandle>;
declare function chooseFileSystemEntries(
  options?: ChooseFileSystemEntriesOptionsFileMultiple,
): Promise<FileSystemFileHandle[]>;
declare function chooseFileSystemEntries(
  options?: ChooseFileSystemEntriesOptionsDirectory,
): Promise<FileSystemDirectoryHandle>;
declare function chooseFileSystemEntries(
  options?: ChooseFileSystemEntriesOptionsDirectoryMultiple,
): Promise<FileSystemDirectoryHandle[]>;
declare function chooseFileSystemEntries(
  options?: ChooseFileSystemEntriesOptionsMultiple,
): Promise<Array<FileSystemDirectoryHandle | FileSystemFileHandle>>;
declare function chooseFileSystemEntries(
  options?: ChooseFileSystemEntriesOptions,
): Promise<FileSystemDirectoryHandle | FileSystemFileHandle>;

interface Window {
  chooseFileSystemEntries: typeof chooseFileSystemEntries;
}
```

**Comment by Ciantic** [comment]
I would argue this is *more useful* than the typing syntax [in the official spec](https://wicg.github.io/native-file-system/).

**Comment by jakearchibald** [comment]
Yeah, you could alias types like that. I didn't do that above since TypeScript doesn't do it for web APIs, and it wouldn't prevent you providing floats.

**Comment by Ciantic** [comment]
Okay. My point is that even though TypeScript does not enforce it, it would be for documenting purposes. Idea would be to do *all* specs in TypeScript, maybe if TS allowed actual `unsigned long long` one day it could be just removed or renamed with global refactoring.

**Comment by mkruisselbrink** [comment]
I don't see specs every going to go away from using WebIDL for their API definitions, but it seems like it should be possible to largely auto-generate typescript from WebIDL (I guess not for the more clever return type bits of chooseFileSystemEntries this does).

And while I'm a big fan of typescript, I don't really want to be maintaining two versions of the API myself, and don't really want to keep un-actionable issues open either. So I think I'll go ahead and close this issue for now, but not sure what a better way would be to keep a typescript definition like this around and up-to-date with potential future changes...

**Comment by RReverser** [comment]
For anyone coming across this thread: I've cleaned up and upstream my typed definitions (which include both latest changes to the APIs, as well as what's *actually* implemented by Chrome) so anyone can use them by

```sh
$ npm install @types/wicg-native-file-system
```

The source is here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wicg-native-file-system/index.d.ts

**Comment by JudahGabriel** [comment]
> For anyone coming across this thread: I've cleaned up and upstream my typed definitions (which include both latest changes to the APIs, as well as what's _actually_ implemented by Chrome) so anyone can use them by
> 
> ```shell
> $ npm install @types/wicg-native-file-system
> ```
> 
> The source is here: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wicg-native-file-system/index.d.ts

The URL has changed: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/wicg-file-system-access/index.d.ts
