### ISSUE TITLE
Additional methods for creating directories/files only if they didn't exist yet

### ISSUE THREAD

**Issue by Anoesj** [WICG/native-file-system#153]
After playing around with the API for a while, I feel both empowered and a little confused. I think the syntax is a bit weird sometimes, especially when it comes to creating files and directories.

When creating a directory, one has to run `directoryHandle.getDirectory('some directory', { create: true })`. This may create the directory, but may also return an existing directory. In some scenarios, that's perfect, but I think in some cases it's not. Personally, I'm missing a `directoryHandle.createDirectory('some directory')` method that creates a directory or rejects if a file/directory with that name already exists and a `directoryHandle.createFile('some file')` method which does the same for files. These methods would be useful in a scenario where you wouldn't expect there to be a directory _“some directory”_ or file _“some file”_ yet. This proposal is an alternative to #107.

### Example of scenario with current syntax
```javascript
// (In async context)

// We want to create a directory named 'some dir', but only if it didn't exist yet, because that would be unexpected behavior.
const dirName = 'some dir';

// Expected behavior would be that no entry named {dirName} exists inside the directory belonging to our directoryHandle yet.
// We can't be sure of that just by running directoryHandle.getDirectory(dirName, { create: true });
// That's why we get the directory first with { create: false }. If this rejects, we know nothing named {dirName} exists yet.
try {
  await directoryHandle.getDirectory(dirName, { create: false });
  dirExists = true;
}
catch {
  dirExists = false;
}

if (dirExists) {
  // Let user know that the an entry with that name already exists.
}
else {
  // We only create the directory if it didn't exist yet. If it did, something unexpected happened and we don't want to proceed.
  const newlyCreatedDir = await directoryHandle.getDirectory(dirName, { create: true });
  // Now do something cool with the newly created directory!
}
```

### Example of scenario with proposed syntax
```javascript
// (In async context)

// We want to create a directory named 'some dir', but only if it didn't exist yet, because that would be unexpected behavior.
const dirName = 'some dir';

// Expected behavior would be that no entry named {dirName} exists inside the directory belonging to our directoryHandle yet.
// That's why we run directoryHandle.createDirectory(dirName), which will reject if an entry named {dirName} already exists.
try {
  const newlyCreatedDir = await directoryHandle.createDirectory(dirName);
  // Now do something cool with the newly created directory!
}
catch {
  // Let user know that the an entry with that name already exists.
}
```

**Thoughts?**

**Comment by mkruisselbrink** [comment]
This seems to be proposing the same functionality as #107, just with a slightly different API? Closing this one to keep the discussion in one place, but let me know if I'm misunderstanding and there is actually something different about the proposed functionality here.
