### ISSUE TITLE
Directory handling lacks relative file path info

### ISSUE THREAD

**Issue by tomayac** [WICG/native-file-system#154]
Opening a directory with `window.chooseFileSystemEntries({type: 'open-directory'})` allows one to recursively iterate over contained subfolders (snippet below), but the lack of something like the old [`webkitRelativePath`](https://wicg.github.io/entries-api/#dom-file-webkitrelativepath) makes this cumbersome, since one needs to keep track of the relative path manually (not shown in the snippet below). 

The [File API](https://www.w3.org/TR/FileAPI) Issue https://github.com/w3c/FileAPI/issues/95 proposes path hashes, but this won't help in this case. 

Can a `File` have a `relativePath` field? Opening this Issue here and not in [w3c/FileAPI/issues](https://github.com/w3c/FileAPI/issues) since the Native File System API's directory handling makes this feature desirable.

```js
const getFiles = async (entries, getRecursive, files = []) => {
  for await (const entry of entries) {
    if (entry.isFile) {
      files.push(await entry.getFile());
    } else if (entry.isDirectory && getRecursive) {
      await getFiles(await entry.getEntries(), getRecursive, files);
    }
  }
  return files;
};

export default async (options = {}) => {
  options.getRecursive = options.getRecursive || false;
  try {
    const handle = await window.chooseFileSystemEntries({
      type: 'open-directory',
    });
    const entries = await handle.getEntries();
    const files = await getFiles(entries, options.getRecursive);
    return 
  } catch (err) {
    throw err;
  }
};
```

**Comment by mkruisselbrink** [comment]
I'd be hesitant to add something like this. What would you use this relative file path for? The API explicitly does not have any methods that actually take a path, so the only thing I can think you might want to use such a path for would be to display it to the user. But when displaying a path to a user different apps might want to format paths differently.

Could you elaborate on what use cases you're thinking of where this would be useful?

**Comment by tomayac** [comment]
Displaying directory trees is something that code editors need:

![VS Studio Code with directory tree](https://raw.githubusercontent.com/alexanderbast/vscode-snazzy/master/sample.jpg)

**Comment by mkruisselbrink** [comment]
But how does having a relative path (that you'd then have to parse again to get its components) help? Also note that we do have `await directory.resolve(child)` that returns the relative path of child inside directory (as an array of names, rather than a single path string). That is async, and you're probably better off just keeping track of it yourself if you're recursively iterating a directory anyway, but it is possible to get the relative path of a file relative to any directory.

**Comment by tomayac** [comment]
I'm comparing the current developer ergonomics to the non-standard `webkitdirectory` attribute. You could easily get all `File`s, and therefore all ` webkitRelativePath`s. See the [example](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory#Example:~:text=When%20the%20change%20event%20occurs%2C%20a,directory%20hierarchies%20is%20generated%20and%20displayed.).

**Comment by mkruisselbrink** [comment]
If we do implement some kind of recursive directory iteration, I can definitely see there being value in getting the relative path at the same time. But without that it seems like the current APIs should be more than sufficient. Also for the specific case of displaying a directory tree like in your screen shot, it seems like (without a recursive iteration API) not having the parse strings to get back the individual path elements in some ways provides better developer ergonomics?

If we do implement recursive directory iteration, I imagine it makes a lot of sense for that to iterate over "relative-path"->"handle" pairs, which seems like it addresses both issues at once.

**Comment by mkruisselbrink** [comment]
Closing this in favor of #173, as I don't think there is much value in this outside of recursive directory iteration.
