### ISSUE TITLE
Spec tone?

### ISSUE THREAD

**Issue by pwnall** [WICG/native-file-system#165]
While reading, I stumbled upon "User agents try to ensure that no partial writes happen".

Should this be "User agents SHOULD ensure that..." or something along those lines? The current state feels like documenting the existing stat of things, and I thought specs aim to guide / dictate the state of things.

Please lmk if there's a new trend I'm unaware of, or if I'm reading wrong specs :smile:

**Comment by mkruisselbrink** [comment]
There is a difference between normative text and informative text. I believe the sentence you're quoting is in a non normative note. In non normative text we try very hard to avoid words such as "should" (in fact bikeshed complains if you use such words) to avoid making it seem like the non normative text is putting restrictions on the implementation. Algorithms are where we dictate what user agents should do, notes are merely there to help non implementers (and implementers) better understand what the algorithms are doing.

**Comment by pwnall** [comment]
Thank you for explaining!

Are the green boxes non-normative? Does this mean we'll need normative text matching them throughout the spec?

**Comment by inexorabletash** [comment]
> Are the green boxes non-normative? Does this mean we'll need normative text matching them throughout the spec?

Yeah...  the bottom of the spec template calls this out:

https://wicg.github.io/native-file-system/#conformance

(I prefer the WHATWG template that calls these out as "Note" more clearly.)
