### ISSUE TITLE
Make files read-only by default

### ISSUE THREAD

**Issue by mgiuca** [WICG/native-file-system#17]
The explainer shows the new `FileSystemFileHandle` API taking a `readOnly` property, with "false" meaning writable and "true" meaning read-only.

This implies that files will be writable by default.

I think it would be less scary if you don't accidentally ask for writable files when you only need to read them. I suggest changing `readOnly` to `writable` and inverting the logic, with "false" the default, meaning read-only, and "true" meaning writable.

**Comment by mkruisselbrink** [comment]
This is how things are currently spec'ed, so closing this.
