### ISSUE TITLE
Define well-known locations

### ISSUE THREAD

**Issue by kenchris** [WICG/native-file-system#18]
In response to https://github.com/w3ctag/design-reviews/issues/390

Other platforms have default locations that can be reused, like

Android:
https://developer.android.com/reference/android/os/Environment#DIRECTORY_ALARMS

Linux:
https://wiki.archlinux.org/index.php/XDG_user_directories
https://cgit.freedesktop.org/xdg/xdg-user-dirs/tree/user-dirs.defaults

**Comment by christianliebel** [comment]
Windows:
https://docs.microsoft.com/de-de/windows/desktop/api/shlobj_core/nf-shlobj_core-shgetknownfolderpath

**Comment by mkruisselbrink** [comment]
Closing this. #144 will need something like this, and other API surfaces might too, but with getSystemDirectory no longer currently specified this isn't currently needed.
