### ISSUE TITLE
createWritable() is not working

### ISSUE THREAD

**Issue by kota-yata** [WICG/native-file-system#182]
some days ago, this code stopped working.
```javascript
const overwrite = document.getElementById("overwrite");
overwrite.addEventListener('click', async () => {
    if (fileHandle) {
        const writer = await fileHandle.createWriter();
        await writer.truncate(0);
        await writer.write(0, left_input.value);
        await writer.close();
        alert("Overwritten")
    } else {
        alert("There is no file to overwrite...");
    }
});
```
So I rewrote the code above to the code below.

```javascript
const overwrite = document.getElementById("overwrite");
overwrite.addEventListener('click', async () => {
    if (fileHandle) {
        const stream = await fileHandle.createWritable();
        await stream.truncate(0);
        await stream.write(left_input.value); //left_input.value is text that I want to overwrite.
        await stream.close();
        alert("Overwritten")
    } else {
        alert("There is no file to overwrite...");
    }
});
```

then
 
```
TypeError: fileHandle.createWritable is not a function
```

Maybe this is simply my mistake, but there was little information in Japanese, and even looking at the issue, I couldn't find a solution.
If I'm wrong, I need a solution, and if it's a bug, I need it fixed ASAP. Please.

**Comment by mkruisselbrink** [comment]
createWriter was only available in chrome versions upto M81, while createWritable is only available in M83 and up (there was no M83 release). M83 should be released to stable for most platforms by now I believe, so if you're getting that error you should try updating your chrome version to make sure you have some M83 version.
