### ISSUE TITLE
 window.getOriginPrivateDirectory is not a function

### ISSUE THREAD

**Issue by dntzhang** [WICG/native-file-system#183]
Google Chrome 已是最新版本
版本 83.0.4103.61（正式版本） （64 位）

**Comment by mkruisselbrink** [comment]
Per the note in the spec (https://wicg.github.io/native-file-system/#api-getoriginprivatefilesystem) "In Chrome this functionality is currently exposed as FileSystemDirectoryHandle.getSystemDirectory({type: "sandbox"})."

Implementing this change is tracked as htttps://crbug.com/1081287
