### ISSUE TITLE
Permission persistence for PWA's?

### ISSUE THREAD

**Issue by twilson7755** [WICG/native-file-system#184]
Can you clarify whether this native file system API will persist the permissions for installed PWA's.  In reading the guidelines outlined in the following link:
https://chromium.googlesource.com/chromium/src/+/lkgr/docs/security/permissions-for-powerful-web-platform-features.md
it seemed that the permissions should be persisted for installed PWA's. However, in trying out the sample editor provided here:
https://googlechromelabs.github.io/text-editor/
after installing it as a PWA, I was still presented with the security prompts when trying to access the same files/directories.  Is this the correct behavior ... if so, unfortunately that would most likely prevent us from being able to utilize it as we had hoped?

**Comment by mkruisselbrink** [comment]
As currently implemented chrome does not persist any permissions. So what you describe is working as intended. This is however a feature we're actively working on; the plan definitely still is that in a future chrome release installed PWAs will be able to regain access to files without always showing permission prompts.

**Comment by twilson7755** [comment]
Appreciate the quick response ... can you give any sort of rough estimate as to when this capability might be available (i.e. within the next year, two years, etc)?

**Comment by mkruisselbrink** [comment]
My rough estimate would be later this year/by the end of the year.

**Comment by twilson7755** [comment]
Hoping to get an update on when this capability for persisting permissions would be available ... this aspect is critical for us to move ahead and utilize this new API?  Specifically we would need it at the folder level ... the ability to create a new file in a specific folder without repeatedly asking for permission each time.
