### ISSUE TITLE
Question about permissions

### ISSUE THREAD

**Issue by jespertheend** [WICG/native-file-system#190]
Does the spec mention anything about the permission state of any children once permission of the parent has been granted?
I.e. can I be sure that I have read access to a child directory once I have received permission for the root directory handle?
I know chrome currently grants access to all child entries once the parent has received permission.
But I was wondering if the spec mentions anything about this or if this is up for the user agent to decide.

**Comment by mkruisselbrink** [comment]
That is what the spec currently requires, yes. The "default" query permission steps merely look at the permissions of their parent. And only for the root entries returned by for example a file picker is this overridden to actually reflect the users intent.
