### ISSUE TITLE
using the native File System with Promises

### ISSUE THREAD

**Issue by davoko** [WICG/native-file-system#194]
Due to the limitations of the minifer my programm uses, I had change from using the File System with Async/Await to writing it with Promises. There I ran into a problem, where my `window.chooseFileSystemEntries({type: 'save-file'}).createWritable().then((w) => w.write(contents)).then((w) => w.close())` code always failed and returned a Type Error message: _TypeError: This writable stream writer has been released and cannot be used to monitor the stream's state_. Everything seems to be working without problem until the **w.write(contents))** function, where the TypeError is being thrown and the stream (w) switches from `{locked: false}` to `{locked: true}`.

First of all is it possible to use the native File System without using Async/Await and does somebody know, why the ´write()´ function always throws out a TypeError?
Also is it possible to unlock the stream?

**Comment by inexorabletash** [comment]
(Aside: I'm assuming you're accounting for `chooseFileSystemEntries()` itself returning a promise, not reflected in your snippet.)

Off the top of my head, the writer is likely being garbage collected between your `then()`s because nothing is holding a reference to it across those calls. A literal transformation of the `await` syntax into `then()` syntax is unfortunately more complicated, something like this:

```js
new Promise({resolve, reject} => {
  const p1 = window.chooseFileSystemEntries({type: 'save-file'});
  p1.then(ref => {
    const p2 = ref.createWritable(); 
    p2.then(w1 => { 
      const p3 = w1.write(contents);
      p3.then(w2 => {
        w2.close().then(resolve, reject);
      }, reject);
    }, reject);
  }, reject);
});
```

A simpler version specific to this case might be:
```
let hold_writer;
window.chooseFileSystemEntries({type: 'save-file'}).then(ref => ref.createWritable()).then(w => {hold_writer = w; return w.write(contents);}).then((w) => w.close())
```

**Comment by RReverser** [comment]
I'm observing the same with async-await snippets like

```js
await (await handle.createWritable({ keepExistingData: false })).close();
```

This used to work before with `createWriter`, which suggests there is some GC-related bug in new implementation of `createWritable`.

**Comment by inexorabletash** [comment]
Thanks - we'll take a look.

**Comment by RReverser** [comment]
Actually, it looks like this breaks on stable as well, just... less frequently? Probably does depend on GC after all.

**Comment by mkruisselbrink** [comment]
Would you mind filing a chromium bug (on crbug.com), preferable with a complete code sample that shows the problem? We definitely have tests that try to write data, and those still pass...

**Comment by mkruisselbrink** [comment]
Closing this, since I don't think there is a spec issue here.

**Comment by RReverser** [comment]
Oh damn, I forgot about this I guess.

**Comment by RReverser** [comment]
Okay, this is now happening even on stable Chrome, so going to submit a crbug.

**Comment by RReverser** [comment]
Here: https://bugs.chromium.org/p/chromium/issues/detail?id=1132506

**Comment by joric** [comment]
> let hold_writer;
> window.chooseFileSystemEntries({type: 'save-file'}).then(ref => ref.createWritable()).then(w => {hold_writer = w; return w.write(contents);}).then((w) => w.close())

This isn't a proper way to do chaining. You need to chain to the "write" call, not to the outer promise. The proper way would be:

```javascript
showSaveFilePicker({suggestedName:name}).then(f=>f.createWritable()).then(f=>f.write(blob).then(()=>f.close()));
```
