### ISSUE TITLE
Prevent file handles from being shared cross-origin

### ISSUE THREAD

**Issue by inexorabletash** [WICG/native-file-system#23]
Although we may revisit this in the future, there may be benefit in making sure FileHandles can't be posted even between cooperating origins.

Proposed by @slightlyoff

**Comment by craigfrancis** [comment]
Is the intention to use something like a random value (an alpha-numeric nonce) to make the file handle serializable?

That would work quite well for the postMeassage() and IndexedDB solutions, where the browser remembers which file(s) the nonce relates to, the domain/origin that can use it, and support easy deleting of those nonce values when clearning client side storage.

Peronsally I’d prefer the file handles to be useless on a different origin, just on the basis that something malicious might be able to send that value to an attacker (admittedly if that was malicious JavaScript, running on the same domain, that is probably game over anyway)... as a theoretical issue, imagine a site that uses a form to POST these references to their server (shouldn’t happen, as it would be useless in a different browser, but you never know), and that forms action is changed to point to a different/malicious domain... the user arrives on that page, along with the file reference, and will now execute malicious JavaScript.

**Comment by inexorabletash** [comment]
> Is the intention to use something like a random value (an alpha-numeric nonce) to make the file handle serializable?

Not necessary. Script would simply not have access to the full serialized state (true today for `File` etc).

**Comment by craigfrancis** [comment]
Interesting... I was aware that you can access a `File` object from an `<input type="file" id="input">` via `document.getElementById('input').files[0]`, but I had assumed it was a reference that could only be used directly, and didn't think it could be stored long term in an IndexedDB ([which can store objects](https://developer.mozilla.org/en-US/docs/Web/API/IDBObjectStore/add); unlike session/localStorage which I'm more familiar with, that only support the storage of strings).

**Comment by inexorabletash** [comment]
Right - Indexed DB (and other APIs) use [structured serialization](https://html.spec.whatwg.org/multipage/structured-data.html#safe-passing-of-structured-data); the details are invisible to script. No need to stringify!

**Comment by mkruisselbrink** [comment]
Closing this, since the spec addresses this. The serialization/deserialization steps check to make sure handles can only be send to same-origin destinations.
