### ISSUE TITLE
Check that the associated permission exists before allowing use of a FileHandle

### ISSUE THREAD

**Issue by inexorabletash** [WICG/native-file-system#24]
In the scenario where the hypothetical "this origin can open writable files" permission has been revoked - either due to an explicit user action, a time-boxed permission grant, self-revocation by the origin, etc - then any previous granted FileHandles should stop working.

This would apply e.g. to FileHandles persisted into a storage mechanism (IDB, History, etc) as well as those hanging around in memory, although presumably we can just leave the persisted ones alone and check at the time of use after they've been rehydrated.

**Comment by mkruisselbrink** [comment]
I believe this is sufficiently addressed in the current spec.
