### ISSUE TITLE
Migration to WebApps WG: Implementor interest?

### ISSUE THREAD

**Issue by LJWatson** [WICG/native-file-system#32]
This specification has been proposed for migration to the [WebApps WG](https://w3c.github.io/charter-drafts/webapps-2019) (which is expected to partly replace the WebPlat WG). For this to happen, we need expressions of interest/intent to commit from at least two implementors.

Please let us know if you plan to implement this specification, or if you can point to any publicly documented expressions of interest from implementors.

The draft WebApps charter will go to the Advisory Committee (AC) within the next two or three weeks, so quick responses may make the difference.

@Chaals @marcoscaceres

**Comment by mkruisselbrink** [comment]
I think it is much too premature to migrate this spec to any WG. There still is a lot of incubation to do.

**Comment by marcoscaceres** [comment]
> There still is a lot of incubation to do.

We feel the same from the Mozilla side. We are sympathetic to the use cases this enables, but we like to see more exploration to help us reach consensus on a suitable permission/security model.
