### ISSUE TITLE
Consider Not Showing Parent Directory

### ISSUE THREAD

**Issue by shellster** [WICG/native-file-system#36]
Please consider not ever allowing the API to know the name of a folder, or it's path, through the API.  For instance, requesting access to the user's Documents directory will also disclose the user's machine username on all major operating systems.  This is potentially a dangerous information disclosure.  If using a common directory, the API already provides a way to request access without needing to know the specific pathing.  If the code request access to the folder, then it would make sense that the API could read all subfolders and files within that folder, but still not know the parent pathing.  I think there is a significant risk to path disclosure of sensitive things like the username that an average user will not think about when granting access via this API.

**Comment by inexorabletash** [comment]
For the [File and Directory Entries API](https://wicg.github.io/entries-api/) which is based on the old Chrome FileSystem proposal, a dragged directory is exposed to script as the root of a virtual file system. The name of the dragged directory is exposed, but not the parent path. E.g. if `C:\Users\josh\Documents\proj` is dragged, script only sees `/proj`.

Agreed that we should do the same thing here; this may be the assumption but not written down anywhere.... ?

**Comment by mkruisselbrink** [comment]
Agreed that we probably shouldn't expose the full path of any entry. As currently described the API doesn't expose paths at all (it just has names for individual entries, and a way to get the parent entry up-to the root of this virtual FS). But yeah, that could be made more explicit.

A interesting question is if there are use cases where having the full path would be helpful. I.e. the similar chrome apps API has a [getDisplayPath](https://developer.chrome.com/apps/fileSystem#method-getDisplayPath) method. Not entirely sure what the use cases for such a method are, but definitely not something I'd be comfortable exposing without much more careful thinking (and likely even not in that case). At least some of the potential use cases for such a thing could perhaps also be solved by having a "show this entry in the system file manager" API... But until people are asking for such a thing, better to just not have any of this.

**Comment by TensorTom** [comment]
I don't think an application would ever need to know the parents' names. No need IMO. Of course it should however have the names of all subdirectories.

**Comment by DanielHerr** [comment]
Having the ability to display the full path is definitely a useful functionality. Almost any text or code editor will show the full path when the user hovers over a file or folder. I have a Chrome app which puts fileSystem.getDisplayPath() into the title attribute of file and folder elements.

**Comment by guest271314** [comment]
@TensorTom If this proposal is a virtual filesystem, similar to `requestFileSystem` the parent directory names can be useful [How to upload and list directories at firefox and chrome/chromium using change and drop events](https://stackoverflow.com/q/39664662) as long as the parent directories can be accurately determined.

**Comment by pwnall** [comment]
The API shape we're currently converging to does not leak any information about the path of a handle. If you have compelling use cases for a `getDisplayPath` method, please open a separate issue to track them. Given the current issue's title, I am going to close it.
