### ISSUE TITLE
Potentially Unwanted Programs Scan

### ISSUE THREAD

**Issue by shaqarava** [WICG/native-file-system#37]
Currently, browsers perform a scan on files when downloaded. I'm not sure how this works under the hood but I know that some browsers have their own internal scanners. Also, that under most operating systems, the default virus/malware scanner is invoked in any newly downloaded path. Any such hooks should also be applied to paths newly created by this API.

**Comment by mkruisselbrink** [comment]
This is definitely something we're considering. A few issues with it though: in chrome, for downloads, the way these checks work is that the file is first downloaded to a temporary file, then checked and finally moved/renamed to its actual destination. That flow won't really work if we want to support an efficient `pwrite` style API (#34) that lets a webapp modify individual bytes of files. Another problem with chrome's downloaded file checking is that it doesn't really work offline, and we explicitly do want this API to work offline as well.

So yeah, it would make sense to have some kind of safe browsing/virus scan checks as part of this, but I'm not sure I see a way of doing that while also keeping a reasonably performant API that actually solves the use cases we want to solve. Perhaps some balance is to only support `pwrite` style writing for "safe" file types (and definitely not for anything that might be executable), and restricting more dangerous file types to a "write this single Blob to the file" API.

**Comment by DanielHerr** [comment]
Is there a reason Chrome or the operating system cannot scan the file after writing has been completed, or before the user attempts to open it?

**Comment by mkruisselbrink** [comment]
"After writing has been completed" might not be very well defined with a pwrite style API. Doing a check after every individual write would probably cause unacceptable performance overhead, but doing the checks later after some delay/some amount of "idle" time could result in a bad user experience where chrome first tells the website that the write was successful (and the website probably then tells the user), but ultimately we end up somehow acting on detected possible malware.

Also unclear how we'd react on anything detected in such a way. Simply deleting the suspected malware files could be problematic, especially if a website is merely modifying an existing file on disk. Maybe we could try to undo the modifications, but that isn't really plausible either (without deep OS integration on certain types of filesystems only).

**Comment by DanielHerr** [comment]
Are you aware of what happens with malware detected when the user selects an existing file to overwrite using the download functionality?
