### ISSUE TITLE
Hash Table For Querying Filesystem Modifications

### ISSUE THREAD

**Issue by shaqarava** [WICG/native-file-system#38]
It would be extremely useful to provide, via this API, a hash table of all files a domain has access to:

[id] [rel path] [hash] [modified date]

That could be the schema unless the hashes can be added to an existing mechanism. It would be a big help as to minimize the amount of directory traversal needed over the wire, which can be an expensive operation. If instead the browser keeps a hash table on behalf of the domain, these operations will be few.

I'm not sure what hashing libraries are most commonly included in modern browsers. All hashing algorithms are not created equal. My favorite algorithm for quickly (Very quickly, nearly 1GBPS) hashing files is [blake2](https://blake2.net/). Such a table would also serve as a big help to sites/apps making use of https://github.com/WICG/writable-files/issues/14

**Comment by mkruisselbrink** [comment]
I'm not entirely sure I understand the request/use case. It seems to me like some combination of #72, and the fact that a website can already store handles in IDB themselves (with whatever metadata they like, such as a hash) covers the request here?
