### ISSUE TITLE
Write to new file

### ISSUE THREAD

**Issue by jcubic** [WICG/native-file-system#39]
It would be probably needed to write to newly created file. Open file picker, user set the name that don't exists and you can have same write and read API (read after first write). Maybe duplicate of #29 or just similar.

**Comment by alinnert** [comment]
Does it need to be a name that doesn't exist? I don't think that system file dialogs care about that. If it strictly needs to be a new file, developers still can check if there's already a file with that name.

**Comment by mkruisselbrink** [comment]
I think `chooseFileSystemEntries({type: 'save-file'})` is exactly this.
