### ISSUE TITLE
FileSystemDirectoryHandle.removeRecursively() seems redundant with FileSystemHandle.remove()?

### ISSUE THREAD

**Issue by pwnall** [WICG/native-file-system#54]
FileSystemDirectoryHandle.removeRecursively() - https://wicg.github.io/native-file-system/#api-filesystemdirectoryhandle-removerecursively

FileSystemHandle.remove() - https://wicg.github.io/native-file-system/#api-filesystemhandle-remove

It seems to me that `remove()` should do the same thing as `removeRecursively()` when called on a directory. Alternatively, we could specify that `remove()` is the equivalent of `rm` for files and `rmdir` (fails for non-empty dirs) for directories. If we go down that route, I'll advocate that we get rid of `removeRecursively()`, because it wouldn't add a new capability.

To be clear, "specify" here doesn't mean "let's write down the entire algorithms for everything". I think that a one-sentence note would be sufficient for the intended consumers of this draft spec.

**Comment by mkruisselbrink** [comment]
The intention of the current API was indeed for `remove()` to not be recursive. #55 is another option for how to change remove/get rid of this redundancy.
