### ISSUE TITLE
Explain what sandboxed file system is.

### ISSUE THREAD

**Issue by mkruisselbrink** [WICG/native-file-system#66]
http://wicg.github.io/native-file-system/#api-getsystemdirectory mentions it returning "the sandboxed file system" without any indication what that actually is. Other than actually formally specifying what this is about, we should at least give some explanation in spec and explainer what this is and why we want to expose it.

(fwiw, it is intended to be more or less the same as the "temporary" filesystem from https://dev.w3.org/2009/dap/file-system/file-dir-sys.html#temporary-vs-persistent-storage. I.e. a quota-managed, origin-scoped private storage area)

**Comment by foolip** [comment]
https://github.com/WICG/native-file-system/issues/10 and https://github.com/WICG/native-file-system/issues/27 seem related.

**Comment by caspervonb** [comment]
So just to be absolutely clear; the implementation can delete the sandbox file-system at its discretion so a user cannot rely on the sandboxed file system being persisted between sessions, correct?

**Comment by inexorabletash** [comment]
The default storage would be "best-effort"; the user agent could indeed remove at any time.

The [persistence permission](https://storage.spec.whatwg.org/#persistence) would apply to the origin's storage, however.
