### ISSUE TITLE
Please detail the need for `resolve()`

### ISSUE THREAD

**Issue by kenchris** [WICG/native-file-system#69]
In response to https://github.com/w3ctag/design-reviews/issues/390

I don't really understand the need for `resolve` so can you add more info for that and maybe show example showing it value

**Comment by pwnall** [comment]
Given an IDE-like application, where a user is working on a project rooted in a directory, being able to `resolve` a handle lets the application show a file's location within the project. The information can be used to focus a directory tree view on the file, or to show the file's path in a title / status bar. This is needed when the file is obtained from a file picker, or (assuming changes to other specs) by dragging the file into the app, or from the OS's "Open with..." menu.

Does this use case help?

**Comment by guest271314** [comment]
@pwnall The use case does not appear to be clear from perspective here. Absolutely unclear at https://wicg.github.io/native-file-system/#dom-filesystemdirectoryhandle-resolve.

Is the expected usage `let res = await dir.resolve(dir)`?

Can you include a brief code snippet demonstrating the use case?

**Comment by pwnall** [comment]
This is probably broken, but I hope it gets the idea across.

```js
// Called when the "Save As" button is clicked in an IDE.
async function onSaveAsClick() {
  const fileHandle = await self.chooseFileSystemEntries({type: 'openFile', readOnly: false});
  if (fileHandle === null) {
    // User canceled out of dialog, abandon the "Save As" intent.
    return;
  }
  
  // Get a directory handle to the root of the IDE's tree view.
  const treeRoot = workspace().treeView().rootHandle();

  const relativePath = treeRoot.resolve(fileHandle);
  if (relativePath === null) {
    // The selected file is outside the workspace.
    await workspace().treeView().hideCursor();
  } else {
    // Highlight the file selected from the picker in the IDE's tree view.
    await workspace().treeView().setCursor(relativePath);
  }

  // TODO: Write the current editor's buffer contents to fileHandle.
}
```

**Comment by guest271314** [comment]
Is the only application context an IDE which `resolve()` is used to "highlight" a path to a file? Still not following what `resolve()` is intended to achieve which is not possible using the values available from `self.chooseFileSystemEntries()`?

**Comment by mkruisselbrink** [comment]
Without resolve() there is no way to compare different handles, so yes, IDE to highlight a path to a file is one option, another one would be launch events where when launching a PWA with a file that is already open might want to focus the window that has that file open rather than opening a new window.

So basically resolve() gives you a way to compare two handles and see if they are in any way related. Since we don't expose paths (or parents) in any way, there is no way to do these things with the rest of the API.

**Comment by guest271314** [comment]
`resolve()` returns `null` or full path to a file handle if permission was granted for the requested directory?

**Comment by foolip** [comment]
Looks like this was removed in commit 5e1146ea7d0bda447dd3890f9ed041bd42987f04, but it remains in EXPLAINER.md as `await dir_ref.resolve(file_ref)`.
