### ISSUE TITLE
net::ERR_FILE_NOT_FOUND when File from getFile() passed to URL.createObjectURL()

### ISSUE THREAD

**Issue by guest271314** [WICG/native-file-system#70]
Context: 
Chromium "App" at `chrome:` protocol
Code:
```
      result = await (await dir.getFile(outputFileName, {
        create: false
      })).getFile(); // File object with type set to "application/octet-stream"
     const blobURL = URL.createObjectURL(result);
```
Result: 
`GET blob:chrome-extension://knldjmfmopnpolahpmmgbagdohdnhkik/104558b5-2be7-4173-baa7-2a96c825f52a net::ERR_FILE_NOT_FOUND`

logged _31_ times at `console`. 

After trying several different approaches was able to compose a workaround to get the `File` converted to a `Blob` and set the `type`. Without using `Blob.stream()` was not able to further process the `File` from `getFile()`

```
      const canNowUseFile = await new Response(result.stream(), {
        headers: new Headers({
          "Content-Type": mimeType
        })
      }).blob();
```

Could not locate any indication in the Explainer or Specification ("Draft Community Group Report, 21 June 2019" https://wicg.github.io/native-file-system/) that the behaviour of `File` from `getFile()` is different from `new File()`; nor how to handle that behaviour (`File` from `getFile()` behaving differently that `new File()` or `new Blob()` when passed to `createObjectURL()`).

Am asking  is the `net::ERR_FILE_NOT_FOUND` result by design?

**Comment by guest271314** [comment]
![getFileNetError](https://user-images.githubusercontent.com/4174848/61258365-db572380-a764-11e9-96ac-f9ce03ea2f81.png)

**Comment by mkruisselbrink** [comment]
Implementation bugs really should be filed on chromium's bug tracker crbug.com. Afaict what you're describing should just work, so not sure what would be going on.

**Comment by guest271314** [comment]
@mkruisselbrink 

> Implementation bugs really should be filed on chromium's bug tracker crbug.com. Afaict what you're describing should just work, so not sure what would be going on.

Well, the code described does not "just work". That is why asked the question if the actual result is by design here, since there are no signs from browsers other than Chromium/Chrome that they will implement Native File System. Evidently your answer to the question at OP is "no", the result is not by design, and is in fact a bug. Am close to completing preliminary testing of the code. When publish the code at GitHub will file a Chromium bug linking to the version which throws the `net` error and post link to Chromium bug at this issue.

**Comment by guest271314** [comment]
@mkruisselbrink  

> Implementation bugs really should be filed on chromium's bug tracker crbug.com.

https://bugs.chromium.org/p/chromium/issues/detail?id=985665

> Afaict what you're describing should just work, so not sure what would be going on. 

Agree, "should" though does not currently "just work". To reproduce comment lines 253-257 and substitute `result` for `merged` file at line 262 at https://github.com/guest271314/native-messaging-mkvmerge/blob/master/app/native-messaging-mkvmerge.js.

**Comment by pwnall** [comment]
Please continue this discussion in the Chrome bug, not in this spec issue. This avoids creating unnecessary work for folks who want to catch up on the discussion behind the spec.
