### ISSUE TITLE
How does the stages rollout look?

### ISSUE THREAD

**Issue by kenchris** [WICG/native-file-system#75]
In response to https://github.com/w3ctag/design-reviews/issues/390

You mention that you will roll this out in stages. For our TAG review, it would be nice if you could detail how you will roll this out so that we know on what to concentrate for now

**Comment by mkruisselbrink** [comment]
Good question. I linked to https://docs.google.com/document/d/11rcS0FdwM8w-s2esacEQxFfp3g2AAI9uD7drH8ARKPA/edit# in the TAG review request, which tries to capture the differences between spec/explainer and (planned) implementation.

In addition I'll also work on annotating the spec itself with which functionality is expected to be available when, and what functionality is still much more in flux.
