### ISSUE TITLE
Experimentation in Electron

### ISSUE THREAD

**Issue by Martin-Pitt** [WICG/native-file-system#8]
Just an idea, but this API could be tested using Electron and see how it feels/works against what pretends to be a completely vanilla web app and creating a polyfill in Electron.

I do have a use-case for an animation editor I wanted to write entirely using Web APIs, but the lack of a good API for writing/saving project files always make it really difficult to bridge. I think with this API may prove a tipping point past which we can in fact start creating high quality tools.

**Comment by dariocravero** [comment]
👍 for electron! https://github.com/suchipi/fs-remote could also come in handy for testing/shimming.
