### ISSUE TITLE
chooseFileSystemEntries should not reject on cancel

### ISSUE THREAD

**Issue by AshleyScirra** [WICG/native-file-system#84]
In my view, rejections are like exceptions - they should only happen under exceptional circumstances.

The user choosing 'Cancel' is not an exceptional circumstance: it's an entirely reasonable and routine thing for the user to change their mind and cancel a dialog.

A good explanation of the difference is the fact the debugger has an option to stop on all exceptions (even caught exceptions). This is useful for catching errors in the debugger. However it is irritating if this breaks the debugger on routine operations, like clicking 'Cancel'.

Currently Chrome rejects the promise returned from `chooseFileSystemEntries` if you cancel the dialog, so you need exception handling to catch the user cancelling, and inspection of the error to identify a routine user-cancelled action vs. actual errors. Instead I'd suggest it resolves with `null` if the user cancels.

**Comment by pwnall** [comment]
I'd be concerned about adding multiple failure modes.

`chooseFileSystemEntries` can also fail due to security permissions, and rejecting in that case is a fairly well-established pattern. So, application code already needs to handle rejections. Asking authors to also handle `null` adds complexity to their codebase, and I'm worried it'd result in lower-quality content.

**Comment by AshleyScirra** [comment]
I think it's justified since there are three possible outcomes that are all handled differently:

1. User picks a file - app reads it
2. User cancels - app does nothing
3. Security/permission/other type of error - app shows follow-up prompt indicating the problem (e.g. an OK dialog with a message like "Unable to open file. Please check you have permission to access it.")

Using a rejection for #2 seems like a bad fit (since it's not an exceptional situation, whereas #3 arguably is), and could increase complexity since you have to actually inspect the type of exception (and possibly match on the message string, which is brittle) to identify the case that the app should respond by doing nothing. On the other hand, returning `null` is easier to check for.

**Comment by mkruisselbrink** [comment]
I agree with @pwnall, I don't think we should add a separate failure mode for "user cancels dialog".
