### ISSUE TITLE
how to use in Worker?

### ISSUE THREAD

**Issue by wmhilton** [WICG/native-file-system#92]
It does not appear that `chooseFileSystemEntries()` is available in Workers. I suppose once serializing fileHandles is possible, the result can be `postMessage`ed to a worker. Is that the intended usage pattern? Until then, is there any way I can experiment with using the API in a Worker thread?

**Comment by inexorabletash** [comment]
That is the intended use pattern. Chrome's implementation of transferability should start soon!

**Comment by wmhilton** [comment]
Awesome! For now I'm using the "sandbox" thing if in a Worker.

Here's my work-in-progress if anyone is interested: https://github.com/isomorphic-git/lightning-fs/blob/feat/native/src/NativeFS.js

I got it working with `isomorphic-git` which is pretty neat. Imagine being able to work with local git repos in a browser IDE! Such potential here.

**Comment by mkruisselbrink** [comment]
In chrome M83 postMessage and IndexedDB support should now be working.
