### ISSUE TITLE
Navigating to directories and clicking "Select Folder" at directory prompt IS user activation.

### ISSUE THREAD

**Issue by guest271314** [WICG/native-file-system#96]
Clicking "Select Folder" at directory prompt IS a user gesture.

`DOMException: User activation is required to request permissions.`

is thrown when navigating from an initially selected directory at `chooseFileSystemEntries()` to the directory where `Select Folder` button is clicked at the same directory prompt initiated by `chooseFileSystemEntries()`.

The fact that the user MUST click to navigate from one directory to a different directory and MUST click `Select Folder` demonstrates the fact that the required user action does take place, at least twice, resulting in the error message being factually incorrect. 

Navigating from a directory to one or more directories and clicking "Select Folder" at directory prompt from `chooseFileSystemEntries()` IS user activation. Logic demands the error should not be thrown as the message is not true.

The specification should to make it clear that user navigation between directories IS "user activation". 

Related https://github.com/WICG/native-file-system/issues/71

**Comment by guest271314** [comment]
Chromium bug https://bugs.chromium.org/p/chromium/issues/detail?id=986107. Native File System is still broken re this matter.

**Comment by guest271314** [comment]
This algorithm for file and folder selection at [4.10.5.1.17 File Upload state (type=file)](https://html.spec.whatwg.org/multipage/input.html#file-upload-state-(type=file)) **does not state** that a folder selected `<input type="file">` **will** be stored in memory and be directly used **later** by Native File System.

Native File System [3.1. The chooseFileSystemEntries() method](https://wicg.github.io/native-file-system/#api-choosefilesystementries) **does not state** that a previously selected directory at HTML`<input type="file">` element will be displayed at the initial directory at 

> Shows a file picker dialog to the user and returns handles for the selected files or directories.

Therefore the behaviour of populating the file picker at Native File System `chooseFileSystemEntries()` execution is **not specified** and should be clearly specified to **not** occcur whatsoever. 

Data is being **leaked** from the HTML Standard `<input type="file">` and to the degree applicable [File API](https://w3c.github.io/FileAPI/) 

> A [FileList](https://w3c.github.io/FileAPI/#dfn-filelist) interface, which represents an array of individually selected files from the underlying system. The user interface for selection can be invoked via <input type="file">, i.e. when the input element is in the File Upload state [[HTML](https://w3c.github.io/FileAPI/#biblio-html)].

to Native File System API. It needs to be made clear that the behaviour is non-standard, not specified. The issue is not user activation, as demonstrated above, the user MUST click at least twice   within the span of the non-specified 5 seconds to navigate out of the directory where the data leak is observable. The issue is that Native File System is using leaked data from another API.

**Comment by mkruisselbrink** [comment]
Closing this. The current spec does indeed trigger user activation at the end of the chooseFileSystemEntries algorithm.
